services:
  nav2_sim:
    build:
      context: .
      dockerfile: Dockerfile
    user: "0:0"
    entrypoint: ["/entrypoint.sh"]
    command: ["bash","-lc","sleep infinity"]
    tty: true
    stdin_open: true
    environment:
      - ROS_DISTRO=iron
      - ROSDEP_AUTO_INSTALL=1
      - BUILD_GZ_CLASSIC=1
      # ---- X11 opcional (só funciona se você exportar DISPLAY no host) ----
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./src:/ws/src:rw
      - build_nav2:/ws/build
      - install_nav2:/ws/install
      - log_nav2:/ws/log
      # Socket X11 (opcional; se não tiver DISPLAY, pode deixar mesmo assim)
      - /tmp/.X11-unix:/tmp/.X11-unix:ro

volumes:
  build_nav2:
    name: nav_gps_ws_build_nav2
  install_nav2:
    name: nav_gps_ws_install_nav2
  log_nav2:
    name: nav_gps_ws_log_nav2
