<?xml version="1.0"?>
<package format="2">
  <name>nav_virtual_lanes</name>
  <version>0.0.0</version>
  <description>The nav_virtual_lanes package</description>

  <maintainer email="your_email@example.com">Your Name</maintainer>

  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>nav2_costmap_2d</build_depend>
  <build_depend>pluginlib</build_depend>
  <build_depend>rclcpp</build_depend>

  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>pluginlib</exec_depend>
  <exec_depend>rclcpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
